### PR TITLE
Center window upon frame-size change

### PR DESCRIPTION
**Pull request by ketan0**
Fixes the issue in #37 by adding a hook to window-size-change-functions.

### CODE REVIEW

**Comment by yantar92** [comment]
Can you still reproduce #37?  It magically disappeared in newer Emacs version for me.

**Comment by ketan0** [comment]
@yantar92 Hmm, I'm on Emacs 26.3, but upon closer inspection mine appears to be a slightly different issue—it mostly occurs when calling `toggle-frame-fullscreen` (though I believe it has popped up in normal window size changes too):

before my change:
noncentering

(and occasionally this happened too when I would exit fullscreen:)
resizeerror

after:
after

I believe this has to do with the fact that `window-size-change-functions` is more comprehensive than `window-configuration-change-hook`, as per the [Emacs manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Window-Hooks.html):

> The hook [`window-configuration-change-hook`] can be also used for tracking changes of window sizes. It is, however, not run when the size of a frame changes or automatic resizing of a minibuffer window (see Minibuffer Windows) changes the size of another window. As a rule, adding a function to window-size-change-functions, see above, is the recommended way for reliably tracking size changes of any window.

In fact, I removed the hook in `window-configuration-change-hook` in the above commit, and it still works.

**Comment by yantar92** [comment]
> Hmm, I'm on Emacs 26.3, but upon closer inspection mine appears to be a slightly different issue—it mostly concerns the window not auto-centering when I call toggle-frame-fullscreen (though I believe it has popped up in normal window size changes too): 

I also had this issue earlier. However, everything works smoothly on Emacs master. 

> I believe the reason is that window-size-change-functions is more comprehensive than window-configuration-change-hook, as per the Emacs manual:

It also makes sense for me. I am now puzzled why setting `window-size-change-functions` is not required on master.

**Comment by anler** [comment]
Ok folks, merged 🤞 Thanks for the help!

**Pull request merged**
